#' Load a cached object
#' @description A cached object is retrieved based on a key generated by the path to the present R script, object name, and the working directory.
#' @return cached object. NULL if no such cache exists. Console messages also accompany the output
#' @param remove_stale_cache If TRUE, removes all files older than 180 days from the cache.
#' @importFrom R.cache loadCache
#' @export

load_cached_object <-
    function(object_name, remove_stale_cache = TRUE) {
        if (remove_stale_cache == TRUE) {
            cache_files <- list.files(paste0(R.cache::getCachePath(), "/", strip_fn(getwd())), full.names = TRUE)
            cache_files %>%
                rubix::map_names_set(file.mtime) %>%
                purrr::map(function(x) difftime(Sys.time(), x, units = "days")) %>%
                purrr::keep(function(x) x > 180) %>%
                names() %>%
                file.remove()
        }

        key <- use_cache_key(object_name = object_name)
        print(key)
        x <- R.cache::loadCache(key=key,
                                dirs = strip_fn(getwd()),
                                onError="error")
        if (!is.null(x)) {
            secretary::typewrite_bold("Cache loaded")
            return(x)
        } else {
            secretary::typewrite_bold("Cache does not exist for this object based on the present script path, working directory, and object name.")
            return(x)
        }
    }
