#' Load a cached object
#' @description A cached object is retrieved based on a key generated by the path to the present R script, object name, and the working directory.
#' @return cached object. NULL if no such cache exists. Console messages also accompany the output/
#' @importFrom R.cache loadCache
#' @export

load_cached_object <-
    function(object_name) {
        key <- use_cache_key(object_name = object_name)
        x <- R.cache::loadCache(key=key,
                                dirs = strip_fn(getwd()),
                                onError="error")
        if (!is.null(x)) {
            secretary::typewrite_bold("Cache loaded")
            return(x)
        } else {
            secretary::typewrite_bold("Cache does not exist for this object based on the present script path, working directory, and object name.")
            return(x)
        }
    }
